apiVersion: v1
kind: Service
metadata:
  name: workshop-shoppingcart-mysql
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 32306
  selector:
    app: workshop-shoppingcart-mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop-shoppingcart-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workshop-shoppingcart-mysql
    spec:
      restartPolicy: Always
      containers:
      - image: golfapipol/workshop-shoppingcart-mysql
        imagePullPolicy: "Always"
        name: workshop-shoppingcart-mysql
        ports:
        - containerPort: 3306